name: acupunctureinthevillage
recipe: lamp
config:
  webroot: web
  php: '8.1'
  via: apache

services:
  appserver:
    build_as_root:
      - apt-get update -y && apt-get install -y unzip git curl
      - curl -OL https://golang.org/dl/go1.22.3.linux-amd64.tar.gz
      - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz
      - echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
      - /usr/local/go/bin/go install github.com/liangyongping/blackhole@latest
      - ln -s /root/go/bin/blackhole /usr/local/bin/blackhole

tooling:
  grav:
    service: appserver
    cmd: bin/grav
  blackhole-export:
    service: appserver
    cmd: blackhole --base-url http://acupunctureinthevillage.lndo.site --output-dir /app/dist --verbose
