name: acupunctureinthevillage
recipe: lamp
config:
  webroot: web
  php: '8.1'
  via: apache
services:
  appserver:
    build_as_root:
      - apt-get update -y && apt-get install -y unzip git
tooling:
  grav:
    service: appserver
    cmd: bin/grav
