enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: false
header-animated: false
header-dark: false
header-transparent: false
sticky-footer: false
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/banner_logo_rev.png:
    name: banner_logo_rev.png
    full_path: banner_logo_rev.png
    type: image/png
    size: 93653
    path: user/themes/quark/images/logo/banner_logo_rev.png
custom_logo_mobile: {  }
